---
# List of system-wide audit policy settings to apply
# Uses ansible.windows.win_audit_policy_system module
audit_configuration_system_policies:
#  - category: Account Logon
#    audit_type:
#      - success
#      - failure
#  - subcategory: File System
#    audit_type:
#      - failure

# List of audit rules to remove
# Uses ansible.windows.win_audit_rule module
audit_configuration_rules_remove:
#  - path: C:\Windows\Temp
#    user: BUILTIN\Users

# List of audit rules to create
# Uses ansible.windows.win_audit_rule module
audit_configuration_rules_create:
#  - path: HKLM:\Software
#    user: BUILTIN\Users
#    rights:
#      - delete
#    audit_flags:
#      - success
