---
# List of scheduled tasks to remove
# Uses community.windows.win_scheduled_task module
task_scheduling_remove:
#  - Incorrect task
#  - Obsoleted task

# List of scheduled tasks to create/enable/disable
# Uses community.windows.win_scheduled_task module
task_scheduling_create:
#  - name: Report system info
#    description: Daily system info update
#    enabled: true
#    actions:
#      - path: cmd.exe
#        arguments: /c systeminfo.exe > \Windows\Temp\systeminfo.txt
#    triggers:
#      - type: daily
#        start_boundary: '00:00:00'
#    username: SYSTEM
