---
- name: Check WinRM service details
  ansible.windows.win_service_info:
    name: WinRM
  register: winrm_service_info

- name: Display WinRM service details
  debug:
    var: winrm_service_info.services[0]

- name: Check WinRM service configuration
  check_mode: false
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      winrm get winrm/config
  register: winrm_config_info
  changed_when: false

- name: Display WinRM service configuration
  debug:
    var: winrm_config_info.output

- name: Check WinRM listener configuration
  check_mode: false
  ansible.windows.win_powershell:
    error_action: stop
    script: |
      winrm enumerate winrm/config/listener
  register: winrm_listener_info
  changed_when: false

- name: Display WinRM listener configuration
  debug:
    var: winrm_listener_info.output
