---
galaxy_info:
  role_name: task_scheduling
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: task_scheduling role
  license: GPLv3+
  min_ansible_version: "2.18"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - windows
    - configuration
dependencies: []
